version: "3"
services:
  postgres:
    image: "postgres:11.8-alpine"
    container_name: codeflix-postgres
    restart: on-failure
    tty: true
    environment:
      - POSTGRES_DB=codeflix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    volumes:
      - "./.docker-data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    container_name: codeflix-localstack
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - "DOCKER_HOST=unix:///var/run/docker.sock"
    volumes:
      - "./.docker-data/localstack:/tmp/localstack"
    ports:
      - "8099:8080"
      - "4572:4572"
  redis:
    image: redis:alpine
    container_name: codeflix-redis
    ports:
      - "6379:6379"
